project:
  type: book
  output-dir: docs

book:
  title: "Models for Multi-State Survival Data"
  subtitle: "Rates, Risks, and Pseudo-Values"
  author: "Per Kragh Andersen & Henrik Ravn"
  reader-mode: true
  sidebar:
    logo: MSBfrontbirds.png
    collapse-level: 1
  page-footer:
    left: |
      Models for Multi-State Survival Data: Rates, Risks, and Pseudo-Values
    right: |
      Built with <a href="https://quarto.org/">Quarto</a>
  cover-image: MSB-cover.png
  favicon: corvos.png
  repo-url: https://github.com/multi-state-book/companion
  chapters: 
    - index.qmd
    - Ch1.qmd
    - Ch2.qmd
    - Ch3.qmd
    - Ch4.qmd
    - Ch5.qmd
    - Ch6.qmd
    - Ch7.qmd
    
execute: 
  warning: false
  message: false
  cache: true

format:
  html:
    #code-block-border-left: true
    code-block-border-left: "#6C6C6C"
    code-block-bg: true
    code-fold: true
    #code-tools:
    #  source: false
    #  toggle: true
    #  caption: "Code"
    code-summary: "Code show/hide"
    fig-width: 11.69
    fig-height: 8.27
    number-depth: 0
    toc-depth: 4
    theme:
      - cosmo
      - msb.scss
       
editor: source

