### Read data 

::: {.panel-tabset}

## R
```{r}
#| label: read-testis-r

testis <- read.csv("data/testis.csv")
# Add extra variables
testis$lpyrs <- log(testis$pyrs)
testis$par2 <- as.numeric(testis$parity < 2)
```
## SAS
```{sas}
#| label: read-testis-sas
#| eval: false 
#| output: false

proc import out=testis
	datafile="data/testis.csv"
	dbms=csv replace;
run;
data testis; 
	set testis; 
	lpyrs = log(pyrs); 
	par2 = (parity>=2); 
run;
```
:::

### Figure 3.1 

::: {.panel-tabset}

## R
```{r}
#| label: figure-3.1-r
#| fig-height: 8.27
#| fig-width: 8.27
#| out-widt: 66%

# Data frames
df1 <- data.frame(x1 = 1900 + c(50, 58, 63, 68, 73), 
                  y1 = rep(0, 5), 
                  x2 = rep(2000, 5), 
                  y2 = 100 - c(50, 58, 63, 68, 73))

df2 <- data.frame(x1 = 1968.25 + c(0, 0, 0, 0, 73-68.25), 
                  y1 = c(68.25 - 50, 68.25 - 58, 68.25 - 63, 68.25 - 68, 0), 
                  x2 = rep(1993, 5), 
                  y2 = 100 - c(50, 58, 63, 68, 73) - 7)

df3 <- data.frame(x1 = c(1968.25, 1993, 1968.25, 1968.25, 1968.25 + 1.75, 1968.25 + 6.75, 1968.25 + 11.75), 
                  y1 = c(0, 0, 0, 15, 20, 25, 30), 
                  x2 = c(1968.25, 1993, 1993, 1993, 1993, 1993, 1993), 
                  y2 = c(68.25 - 50, 100 - 57, 0, 15, 20, 25, 30) 
                  )

# For labels
D <- tapply( testis$cases, list( testis$age, testis$cohort ), sum )
Y <- tapply( testis$pyrs, list( testis$age, testis$cohort ), sum )
x <- outer( unique( testis$age )+c(17.5,rep(2.5,4)),
            unique( testis$cohort )+2.5,
            "+" )
x[1,] <- x[1,]-c(0,3,3,3,2)
y <- outer( c(13,17,22,27,32), rep(1,5), "*" )

label_data <- data.frame(x = x[!is.na(Y)], 
                         y = y[!is.na(Y)], 
                         label = paste( round( Y/10^4 )[!is.na(Y)] )
                         )
label_data2 <- data.frame(x = 1956, y = 47.5, label = "PY (10,000)")

# Create plot
library(ggplot2)
theme_general <- theme_bw() +
  theme(legend.position = "bottom", 
        text = element_text(size = 16), 
        axis.text.x = element_text(size = 16), 
        axis.text.y = element_text(size = 16))

fig3.1 <- ggplot(df1) + 
  geom_vline(xintercept = c(1968.25, 1993),
             size = 1, linetype = "dotted") +
  geom_hline(yintercept = c(0, 15, 20, 25, 30),
             size = 1, linetype = "dotted") +
  geom_segment(aes(x = x1, y = y1, 
                   xend = x2, yend = y2), 
               data = df1,
               size = 1, linetype = "dotted") + 
  geom_segment(aes(x = x1, y = y1, 
                   xend = x2, yend = y2), 
               data = df2,
               size = 1.5) + 
  geom_segment(aes(x = x1, y = y1, 
                   xend = x2, yend = y2), 
               data = df3,
               size = 1.5) + 
  theme_general + 
  xlab("Calendar time") + 
  ylab("Age (years)") + 
  scale_x_continuous(expand = expansion(mult = c(0.005, 0.005)),
                     limits = c(1950, 2000), 
                     breaks = seq(1950, 2000, 10)) +
  scale_y_continuous(expand = expansion(mult = c(0.005, 0.005)), 
                     limits = c(0, 50), 
                     breaks = seq(0, 50, 10)) + 
  geom_label(aes(x = x, y = y, label = label), size = 5, label.size = NA,
             hjust = 1.1, vjust = 0.7, 
             data = label_data) + 
  theme(plot.margin=unit(c(0.75, 0.75, 0.75, 0.75), "cm"))

fig3.1
```
:::

### Table 3.5 

::: {.panel-tabset}

## R
```{r}
#| label: table-3.5-r
library(broom)
library(lmtest)

# Column 1
options(contrasts=c("contr.treatment", "contr.poly"))
testis$age <- as.factor(testis$age)
testis$age <- relevel(testis$age, ref = '20')
summary(glm(cases ~ offset(lpyrs) + par2 + age, data = testis, family = poisson))
# Column 2
testis$motherage <- as.factor(testis$motherage)
testis$motherage <- relevel(testis$motherage, ref = "30")
testis$cohort <- as.factor(testis$cohort)
testis$cohort <- relevel(testis$cohort, ref = "1973")
summary(poisfull<-glm(cases ~ offset(lpyrs) + par2 + age + motherage + cohort, 
                      data = testis,family = poisson))

tidy(poisfull, exponentiate = TRUE, conf.int = TRUE)

# LRT for mother's age
poismage<-glm(cases ~ offset(lpyrs) + par2 + age + cohort, 
              data = testis,family = poisson)
lrtest(poisfull,poismage)

# LRT for birth cohort of son
poiscohort<-glm(cases ~ offset(lpyrs) + par2 + age + motherage, 
                data = testis,family = poisson)
lrtest(poisfull,poiscohort)

# LRT parity and age
poisinteract<-glm(cases ~ offset(lpyrs) + par2 + age + motherage + cohort + par2*age, 
                  data = testis, family = poisson)
lrtest(poisfull,poisinteract)

# HR for seminomas
tidy(glm(semi ~ offset(lpyrs) + par2 + age + motherage + cohort, 
         data = testis, family = poisson),
     exponentiate = T, conf.int = T)
# HR for non-seminomas
tidy(glm(nonsemi ~ offset(lpyrs) + par2 + age + motherage + cohort, 
         data = testis, family = poisson),
     exponentiate = T, conf.int = T)
```

## SAS
```{sas}
#| label: table-3.5-sas
#| eval: false 
#| output: false

* Column 1; 
proc genmod;
	class age (ref='20') par2 (ref='1');
	model cases=par2 age/dist=poi offset=lpyrs type3;
	estimate 'RR' par2 1 -1/exp;
run;
* Column 2; 
proc genmod;
	class age (ref='20') motherage(ref='30') cohort(ref='1973') par2 (ref='1');
	model cases=par2 age motherage cohort/dist=poi offset=lpyrs type3;
	estimate 'RR' par2 1 -1/exp;
run;
* In-text interaction test; 
proc genmod;
	class age (ref='20') motherage(ref='30') cohort(ref='1973') par2 (ref='1');
	model cases=par2 age motherage cohort par2*age/dist=poi offset=lpyrs type3;
run;
* seminomas;
proc genmod;
	class age (ref='20') motherage(ref='30') cohort(ref='1973') par2 (ref='1');
	model semi=par2 age motherage cohort/dist=poi offset=lpyrs type3;
	estimate 'RR' par2 1 -1/exp;
run;
* non-seminomas;
proc genmod;
	class age (ref='20') motherage(ref='30') cohort(ref='1973') par2 (ref='1');
	model nonsemi=par2 age motherage cohort/dist=poi offset=lpyrs type3;
	estimate 'RR' par2 1 -1/exp;
run;
```
:::