```{r}
#| label: read-leader-r
#| echo: false
leader <- read.csv("c:/Users/hnrv/OneDrive - Novo Nordisk/Book/leader/data/leader_mi_3p.csv")
leader_mi <- subset(leader, type == "recurrent_mi")
```

### Read data

Assume that the LEADER data set is loaded in data set `leader_mi`.

### Figure 4.20 

::: {.panel-tabset}
## R
```{r}
#| label: figure-4.20-r
#| out-width: 90%

library(ggplot2)
theme_general <- theme_bw() +
  theme(
    legend.position = "bottom",
    text = element_text(size = 20),
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20)
  )

ghosh_lin_nonpar_mcf <- function(endpointdat) {
  # Fit NAa
  NAa_fit <- survfit(
    Surv(start, stop, status == 1) ~ treat,
    data = endpointdat,
    id = id,
    ctype = 1
  )
  
  # Fit KM
  KM_fit <- survfit(
    Surv(start, stop, status == 2) ~ treat,
    data = endpointdat,
    id = id,
    ctype = 1
  )
  
  # Adjust hat(mu)
  mu_adj <-
    c(cumsum(KM_fit$surv[1:KM_fit$strata[[1]]] * c(0, diff(NAa_fit$cumhaz[1:NAa_fit$strata[[1]]]))),
      cumsum(KM_fit$surv[(KM_fit$strata[[1]] + 1):(KM_fit$strata[[1]] + KM_fit$strata[[2]])] *
               c(0, diff(NAa_fit$cumhaz[(NAa_fit$strata[[1]] + 1):(NAa_fit$strata[[1]] + NAa_fit$strata[[2]])]))))
  
  dat_adj <- data.frame(
    mu = mu_adj,
    time = NAa_fit$time,
    treat = c(
      rep("Liraglutide", NAa_fit$strata[[1]]),
      rep("Placebo", NAa_fit$strata[[2]])
    ),
    type = rep(
      "Mortality treated as a competing risk (CL)",
      length(NAa_fit$time)
    )
  )
  
  dat_unadj <- data.frame(
    mu = NAa_fit$cumhaz,
    time = NAa_fit$time,
    treat = c(
      rep("Liraglutide", NAa_fit$strata[[1]]),
      rep("Placebo", NAa_fit$strata[[2]])
    ),
    type = rep("Mortality treated as censoring (NA)", length(NAa_fit$time))
  )
  
  dat_adj$both <- with(dat_adj, paste(type, treat, sep = ", "))
  dat_unadj$both <- with(dat_unadj, paste(type, treat, sep = ", "))
  
  pdat <- rbind(dat_adj, dat_unadj)
  
    ggplot(aes(x = time  * 1 / (365.25 / 12), y = mu), data = pdat) +
    geom_step(aes(linetype = both), linewidth = 1.05) +
    xlab("Time since randomization (months)") +
    ylab("Expected number of events per subject") +
    scale_color_discrete("Treatment") +
    scale_linetype_manual("", values = c("dotdash", "dotted", "solid", "dashed")) +
    theme_general +
    theme(
      legend.position = "bottom",
      legend.margin = margin(t = -25),
      legend.direction = "vertical",
      legend.box = "horizontal",
      text = element_text(size = 20),
      legend.text = element_text(size = 18),
      legend.key.width = unit(3, "cm")
    ) +
    scale_x_continuous(
      expand = expansion(mult = c(0.005, 0.05)),
      limits = c(0, 65),
      breaks = seq(0, 65, by = 12)
    ) +
    scale_y_continuous(
      expand = expansion(mult = c(0.005, 0.05)),
      limits = c(0, 0.13),
      breaks = seq(0, 0.13, by = 0.02)
    )
  
}

fig4.20 <- ghosh_lin_nonpar_mcf(endpointdat = leader_mi)
fig4.20
```
## SAS
```{sas}
#| label: figure-4.20-sas
#| eval: false 
#| output: false

/* Using "fine-gray model" in PHREG gives an alternative solution to 
  the estimator for CMF using the Breslow type estimator for 
  the baseline mean function (see p. 199 in book). The estimator is not
	exactly the same as Cook-Lawless because of a different procedures 
	for ties of terminating events and censorings. If no ties 
	(or no censorings) it equals Cook & Lawless */

* NELSON-AALEN; 
proc phreg data=leader_mi noprint;
	model stop*status(0 2)=/entry=start;
	id id;
	strata treat;
  baseline out=na_data cumhaz=naa;
run;
data na_est;
	set na_data; 
	type = "Nelson-Aalen";
	cumevent = naa; 
	treat_type = trim(treat) || ", "  || type; 
run; 

* COOK & LAWLESS (GHOSH & LIN);
proc phreg data=leader_mi noprint;
  model (start, stop)*status(0)=/eventcode=1; 
  strata treat;
  baseline out=gl_data cif=cuminc;
run;
data gl_est;
	set gl_data; 
	type = "Ghosh & Lin";
	cumevent = -log(1-cuminc); 
	treat_type = trim(treat) || ", " || type; 
run; 
data comb; 
	set na_est gl_est; 
	time = stop/(365.25/12);
	drop naa cuminc;
run;
proc sgplot data=comb;
	step x=time y=cumevent/group=treat_type justify=left;
	xaxis grid values=(0 to 60 by 12);
	yaxis grid values=(0 to 0.12 by 0.02);
	label time="Time since randomisation (months)";
	label cumevent="Expected number events per subject"; 
run; 


/*** Calc Cook & Lawless or (Ghosh & Lin (GL)) estimator for CMF by hand ***/
/* First create KM data for death */
proc phreg data=leader_mi noprint;
  model stop*status(0 1)= / entry=start; /* status=2=death */
  strata treat;
  baseline out=kmdata survival=km / method=pl ;
run;
/* Second create NAa data */
proc phreg data=leader_mi noprint;
  model stop*status(0 2)= / entry=start; /* status=1=event */
  strata treat;
  baseline out=nadata cumhaz=na;
run;
/* Use NA data to calculate dA(u), i.e., increments in NAa */
data na;
  set nadata;
  dAu=na-lag(na);
  if stop=0 then dAu=0;
  keep treat stop dAu na;
run;
/* merge NAa and KM data */
data merged;
  merge na kmdata;
  by treat stop;
run;
/* multiply S(u-) and dA(u) */
data fill;
   set merged;
   retain _km;
   if not missing(km) then _km=km;
   else km=_km;
   /* S(u-) */
   S_uminus=lag(km);
   if stop=0 then S_uminus=1;

   if dAu=. then dAu=0;
   GLfactor=S_uminus*dAu;
   keep treat stop na dAu S_uminus GLfactor;
run;
data GLdata;
  set fill;
  by treat;
  if first.treat then GL=0;
  else GL+GLfactor;
	time = stop/(365.25/12);
run;
proc sgplot data=GLdata;
  step x=time y=na / group=treat;
  step x=time y=GL / group=treat;
	xaxis grid values=(0 to 60 by 12);
	yaxis grid values=(0 to 0.12 by 0.02);
	label time="Time since randomisation (months)";
	label na="Expected number events per subject"; 
run;
```
:::


### In-text: LWYY and Ghosh-Lin models  

::: {.panel-tabset}

## R
```{r}
#| label: in-text-lwyy-ghoshlin-r

library(survival)
fit1 <- coxph(Surv(start, stop, status == 1) ~ treat + cluster(id), 
              data = leader_mi, ties = "breslow")
summary(fit1)

# Ghosh-Lin model - Mortality treated as competing risk
library(mets)
fit2 <- recreg(Event(start, stop, status) ~ treat + cluster(id),
               data = leader_mi, cause = 1, cens.code = 0, death.code = 2)
summary(fit2)

```

## SAS
```{sas}
#| label: in-text-lwyy-ghoshlin-sas
#| eval: false 
#| output: false

title 'LWYY model';
proc phreg data=leader_mi covs(aggregate);
  class treat(ref="0");
  model (start, stop)*status(0 2) = treat / rl; 
  id id;
run;

title 'Ghosh-Lin model';
proc phreg data=leader_mi covs(aggregate);
  class treat(ref="0");
  model (start, stop)*status(0) = treat / rl
		eventcode=1 convergelike=1E-9; 
  id id;
run;
```
:::