```{r}
#| echo: false
leader <- read.csv("c:/Users/hnrv/OneDrive - Novo Nordisk/Book/leader/data/leader_mi_3p.csv")
```

### Read data

::: panel-tabset

## R

Assume that the LEADER data set is loaded in data set `leader`.

```{r}
#| label: read-leader-r

# One data set per recurrent endpoint type
leader_mi <- subset(leader, type == "recurrent_mi")
leader_3p <- subset(leader, type == "recurrent_comb")
```

## SAS

```{sas}
#| label: read-leader-sas
#| eval: false 
#| output: false
data leader_mi; 
	set leader; 
	where type = "recurrent_mi"; 
run; 
```

:::

### Figure 2.15

::: panel-tabset
## R

```{r}
#| label: figure-2.15-r

library(ggplot2)
theme_general <- theme_bw() +
  theme(legend.position = "bottom",
        legend.title=element_blank(),
        legend.text = element_text(size = 20),
        legend.key.size = unit(2,"line"),
        text = element_text(size = 20), 
        axis.text.x = element_text(size = 20), 
        axis.text.y = element_text(size = 20)) 

# Nelson-Aalen estimate of the cumulative hazard of MI
library(survival)
fit <- survfit(Surv(start, stop, status == 1) ~ treat, data = leader_mi,
               id = id, ctype = 1)

plotdata <- data.frame(cumhaz = fit$cumhaz, time = fit$time,
                       treat = c(rep("Placebo", fit$strata[[1]]),
                                 rep("Liraglutide", fit$strata[[2]])))

fig2.15 <- ggplot(aes(x = time * 1 / (365.25 / 12), y = cumhaz), data = plotdata) +
  geom_step(aes(linetype = treat), linewidth = 1) +
  scale_linetype_discrete("Treatment") +
  ylab("Cumulative hazard") +
  xlab("Time since randomization (months)") +
  theme_bw() +
  scale_x_continuous(expand = expansion(mult = c(0.005, 0.05)),
                     limits = c(0, 65), breaks = seq(0, 60, by = 12)) +
  scale_y_continuous(expand = expansion(mult = c(0.005, 0.05)),
                     limits = c(0, 0.12), breaks = seq(0, 0.12, by = 0.02)) +
  theme_general

fig2.15
```

## SAS

```{sas}
#| label: figure-2.15-sas
#| eval: false 
#| output: false
* Nelson-Aalen estimates; 
proc phreg data=leader_mi noprint;
	model stop*status(0 2)=/entry=start;
	id id;
	strata treat;
  baseline out=na_data cumhaz=naa;
run;
data na_est;
	set na_data; 
	time = stop/(365.25/12);
run; 
proc sgplot data=na_est;
	step x=time y=naa / group=treat justify=left;
	xaxis grid values=(0 to 60 by 12);
	yaxis grid values=(0 to 0.12 by 0.02);
	label time="Time since randomisation (months)";
	label cumevent="Cumulative hazard"; 
run; 
```

:::

### Table 2.15

::: panel-tabset
## R

```{r}
#| label: table-2.15-r

# Cox model first event
library(survival)
coxph(Surv(start, stop, status == 1) ~ treat,
      data = subset(leader_mi, eventno == 1), method = "breslow",)
    
# AG Cox type
coxph(Surv(start, stop, status == 1) ~ treat, data = leader_mi,
                   method = "breslow")

# AG model, piece-wise constant hazards
# Calculating cuts -> 5
alltimes <- seq(0,max(leader_mi$stop),length=99)
FunctionIntervalM <- function(a,b) {
  seq(from=min(a), to = max(a), by = (max(a)-min(a))/b)
}
cuts <- FunctionIntervalM(a = alltimes, b = 5)
cut_data <- survSplit(Surv(start, stop, status == 1) ~ .,
                      leader_mi,
                      cut = cuts[-1],
                      episode = "timegroup")
coxph(Surv(start, stop, event) ~ treat + strata(timegroup), data = cut_data)

# PWP 2nd event
coxph(Surv(start, stop, status == 1) ~ treat,
                     method = "breslow", subset = (eventno == 2),
                     data = leader_mi)

# PWP 3rd event
coxph(Surv(start, stop, status == 1) ~ treat,
                   method = "breslow", subset = (eventno == 3),
                   data = leader_mi)

# PWP 4th event
coxph(Surv(start, stop, status == 1) ~ treat,
                   method = "breslow", subset = (eventno == 4),
                   data = leader_mi)

# PWP 5th event
coxph(Surv(start, stop, status == 1) ~ treat,
                   method = "breslow", subset = (eventno == 5),
                   data = leader_mi)

# PWP all
coxph(Surv(start, stop, status == 1) ~ treat + strata(eventno),
                   method = "breslow",
                   data = leader_mi)


```

## SAS

```{sas}
#| label: table-2.15-sas
#| eval: false 
#| output: false
proc sort data=leader_mi;
  by eventno;
run;

* AG Cox type;
proc phreg data=leader_mi;
  model stop*status(0 2)= treat / entry=start; 
run;

* Cox model first event and PWP models 2nd, ..., 5th event;
proc phreg data=leader_mi;
  where eventno<=5;
  model stop*status(0 2)= treat / entry=start; 
	by eventno;
run;

* PWP model all events;
proc phreg data=leader_mi;
  model stop*status(0 2)= treat / entry=start; 
	strata eventno;
run;
```

:::
