### Section 5.8.3, p. 213: Mao-Lin models

```{r}
#| echo: false
leader_mi <- read.csv("c:/Users/hnrv/OneDrive - Novo Nordisk/Book/leader/data/leader_mi.csv")
leader_3p <- read.csv("c:/Users/hnrv/OneDrive - Novo Nordisk/Book/leader/data/leader_3p.csv")
```
Assume that the LEADER data sets are loaded.

::: {.panel-tabset}

## R

```{r}
#| label: leader-r
library(mets)
options(contrasts=c("contr.treatment", "contr.poly"))
# Mao-Lin model for recurrent MI+death 
fitML_mi <- recreg(Event(start, stop, status) ~ factor(treat) + cluster(id),
               data = leader_mi, cause = c(1,2), cens.code = 0, death.code = 2)
summary(fitML_mi)

# Mao-Lin model and non-CV deaths incorrectly treated as censoring 
fit_3pCENS <- recreg(Event(start, stop, status) ~ treat + cluster(id),
               data = leader_3p, cause = c(1,2,3), cens.code = c(0,4), death.code = 3)
summary(fit_3pCENS)

# Mao-Lin model for 3p-MACE and non-CV deaths treated as competing risks
fit_3pCR <- recreg(Event(start, stop, status) ~ treat + cluster(id),
               data = leader_3p, cause = c(1,2,3), cens.code = 0, death.code = c(3,4))
summary(fit_3pCR)
```

## SAS

```{sas}
#| label: leader-sas
#| eval: false 
#| output: false
* recurrent MI+death;
data mi; 
	set leader_mi;
	event=status in (1 2);
  output;
	if status=2 then do;
		event=2;
    start=stop;
    stop=stop+0.5;
		output;
	end;
run;
* Mao-Lin model for recurrent MI+death ; 
proc phreg data=mi covs(aggregate);
  model (start, stop)*event(0) = treat / eventcode=1 rl  convergelike=1E-9; 
  id id;
run;

                             Analysis of Maximum Likelihood Estimates

                   Parameter     Standard                               Hazard     95% Hazard Ratio
 Parameter   DF     Estimate        Error   Chi-Square   Pr > ChiSq      Ratio    Confidence Limits

 treat        1     -0.15903      0.05711       7.7559       0.0054      0.853      0.763      0.954


* recurrent 3p-MACE non-CV deaths incorrectly treated as censoring;
data macecens; 
	set leader_3p;
	event=status in (1 2 3);
  if status=4 then event=0;
  output;
	if status=3 then do;
		event=2;
    start=stop;
    stop=stop+0.5;
		output;
	end;
run;
* Mao-Lin model and non-CV deaths incorrectly treated as censoring; 
proc phreg data=macecens covs(aggregate);
  model (start, stop)*event(0) = treat / eventcode=1 rl  convergelike=1E-9; 
  id id;
run;
 
                              Analysis of Maximum Likelihood Estimates

                   Parameter     Standard                               Hazard     95% Hazard Ratio
 Parameter   DF     Estimate        Error   Chi-Square   Pr > ChiSq      Ratio    Confidence Limits

 treat        1     -0.18265      0.05902       9.5754       0.0020      0.833      0.742      0.935



* recurrent 3p-MACE;
data mace; 
	set leader_3p;
	event=status in (1 2 3);
  if status=4 then event=2;
  output;
	if status=3 then do;
		event=2;
    start=stop;
    stop=stop+0.5;
		output;
	end;
run;
* Mao-Lin model for 3p-MACE and non-CV deaths treated as competing risks; 
proc phreg data=mace covs(aggregate);
  model (start, stop)*event(0) = treat / eventcode=1 rl convergelike=1E-9;
  id id;
run;

                             Analysis of Maximum Likelihood Estimates

                   Parameter     Standard                               Hazard     95% Hazard Ratio
 Parameter   DF     Estimate        Error   Chi-Square   Pr > ChiSq      Ratio    Confidence Limits

 treat        1     -0.18340      0.05898       9.6698       0.0019      0.832      0.742      0.934

```
:::